Write-Host "--- Ollama Pulls & Model Creation ---"
Write-Host "This script does NOT execute the commands. It prints the necessary commands to run manually."
Write-Host ""
Write-Host "Step 1: Pull base models from Ollama"
Write-Host "----------------------------------------"
Write-Host "powershell -File .\\scripts\\win\\ollama_pull.ps1"
Write-Host ""
Write-Host "Step 2: Create local custom models"
Write-Host "------------------------------------"
Write-Host "powershell -File .\\scripts\\win\\ollama_create_local_models.ps1"
Write-Host ""
Write-Host "Done. Please run the commands above in your terminal."
