# LangGraph Orchestrator Configuration
# Policies und Limits für Workflow-Execution

# === Global Execution Policies ===
max_steps: 20  # Maximum Steps pro Workflow (Endlos-Loop-Schutz)
retry_budget: 10  # Globales Retry-Budget für alle Steps
execution_timeout_s: 3600  # Max. Gesamtlaufzeit eines Workflows (1h)

# === Resource Management ===
gpu_management:
  max_parallel_gpu_tasks: 1  # Nur ein GPU-Task gleichzeitig
  gpu_timeout_s: 300  # GPU-Task Timeout (5min)
  gpu_cooldown_s: 10  # Pause zwischen GPU-Tasks
  gpu_memory_threshold_mb: 8000  # Min. freier GPU-Speicher

# Task-Prioritäten (niedrigere Zahl = höhere Priorität)
task_priorities:
  txt2img: 1
  img2img: 1
  upscale: 2
  anim: 3
  asr: 1
  tts: 1
  upload_youtube: 4
  upload_tiktok: 4
  upload_instagram: 4

# === Role-Based Permissions ===
role_permissions:
  guest:
    allowed_actions:
      - "txt2img"
      - "asr"
      - "tts"
    max_steps_per_workflow: 3
    max_concurrent_workflows: 1
    max_artifacts_per_workflow: 2
    disabled_features:
      - "upscale"
      - "upload_youtube"
      - "upload_tiktok"
      - "upload_instagram"
      - "anim"
    
  user:
    allowed_actions:
      - "txt2img"
      - "img2img" 
      - "upscale"
      - "anim"
      - "asr"
      - "tts"
      - "upload_youtube"
      - "upload_tiktok"
    max_steps_per_workflow: 15
    max_concurrent_workflows: 3
    max_artifacts_per_workflow: 10
    disabled_features:
      - "upload_instagram"  # Requires special permission
    
  admin:
    allowed_actions: "*"  # All actions allowed
    max_steps_per_workflow: 50
    max_concurrent_workflows: 10
    max_artifacts_per_workflow: 50
    disabled_features: []  # No restrictions

# === Step-Specific Policies ===
step_policies:
  txt2img:
    max_retries: 2
    timeout_s: 60
    requires_gpu: true
    cooldown_s: 5
    validation:
      prompt_max_length: 500
      max_resolution: 1024
      
  img2img:
    max_retries: 2
    timeout_s: 90
    requires_gpu: true
    cooldown_s: 5
    validation:
      prompt_max_length: 500
      max_input_size_mb: 50
      
  upscale:
    max_retries: 1
    timeout_s: 120
    requires_gpu: true
    cooldown_s: 10
    validation:
      max_input_size_mb: 100
      max_scale_factor: 4
      
  anim:
    max_retries: 1
    timeout_s: 300
    requires_gpu: true
    cooldown_s: 15
    validation:
      max_duration_s: 30
      max_input_size_mb: 50
      
  asr:
    max_retries: 2
    timeout_s: 60
    requires_gpu: false
    cooldown_s: 0
    validation:
      max_audio_duration_s: 600
      max_file_size_mb: 100
      
  tts:
    max_retries: 2
    timeout_s: 30
    requires_gpu: false
    cooldown_s: 0
    validation:
      max_text_length: 1000
      
  upload_youtube:
    max_retries: 3
    timeout_s: 600
    requires_gpu: false
    cooldown_s: 30
    validation:
      max_file_size_mb: 2000
      max_title_length: 100
      max_description_length: 5000
      
  upload_tiktok:
    max_retries: 3
    timeout_s: 300
    requires_gpu: false
    cooldown_s: 20
    validation:
      max_file_size_mb: 500
      max_description_length: 300
      
  upload_instagram:
    max_retries: 3
    timeout_s: 300
    requires_gpu: false
    cooldown_s: 15
    validation:
      max_file_size_mb: 100
      max_caption_length: 2200

# === Monitoring & Alerting ===
monitoring:
  enable_performance_tracking: true
  enable_error_alerting: true
  log_all_state_transitions: true
  
  # Thresholds für Alerts
  alert_thresholds:
    workflow_failure_rate: 0.3  # 30% Failure Rate
    avg_execution_time_s: 300   # 5min Average
    gpu_utilization: 0.9        # 90% GPU Usage
    memory_usage_mb: 16000      # 16GB RAM Usage
    
  # Metrics Collection
  metrics:
    - "workflow_duration"
    - "step_execution_time"
    - "gpu_utilization"
    - "memory_usage"
    - "artifact_size"
    - "error_rate"

# === Error Handling ===
error_handling:
  auto_retry_on_errors:
    - "ResourceNotAvailableError"
    - "TemporaryNetworkError"
    - "ComfyUIBusyError"
    
  critical_errors:
    - "OutOfMemoryError"
    - "GPUError"
    - "FileSystemError"
    - "AuthenticationError"
    
  # Circuit Breaker Pattern
  circuit_breaker:
    failure_threshold: 5  # Nach 5 Fehlern: Circuit öffnen
    recovery_timeout_s: 300  # 5min Recovery-Zeit
    half_open_max_calls: 3  # Max. 3 Test-Calls im Half-Open State

# === Persistence ===
persistence:
  save_state_every_step: true
  state_retention_days: 7
  artifact_cleanup_days: 30
  
  # State-Snapshots für Recovery
  snapshots:
    enable: true
    interval_steps: 5  # Snapshot alle 5 Steps
    max_snapshots_per_workflow: 10

# === Development & Debug ===
debug:
  enable_verbose_logging: false
  log_state_transitions: true
  enable_performance_profiling: false
  save_intermediate_artifacts: false
  
  # Test-Modi
  test_mode:
    enable: false
    mock_gpu_operations: false
    mock_external_services: false
    fast_execution: false  # Verkürzte Timeouts für Tests